/**
  * Created by AnthonyAbercrombie on 7/5/17.
  */

import scala.util.parsing.json.JSONObject

abstract class CassandraTable

def KafkaParser(kafkaLog : String) : Seq[String] = {
  // Parses a Kafka log [kafkaLog] and returns a sequence of strings with json
  // structure [plumeRecords]
  ???
}

def PlumeParser(plumeRecords : Seq[String]) : Seq[CassandraRow] = {
  // Parses a sequence of strings with json structure [plumeRecords], extracts
  // geographically relevant data, and returns a sequence of Cassandra
  // rows for a geographically enriched Cassandra table [plumeGeoRows].
  ???
}

def GoogleMapsRequester(lat: Double, long: Double, GOOGLEMAPS: String) : String = {
  // Takes a latitude coord [lat], a longitude coord [long], and a
  // Google Maps API key [GOOGLEMAPS]. These arguements are then
  // factored into an API call. The results of the API call are then
  // returned as a json string [googleMapsResult]
  val base_url = f"https://maps.googleapis.com/maps/api/geocode/json?latlng=$lat%f,$long%f&key=$GOOGLEMAPS%s"
  ???
}

/**
  * Executes a query that gets distinct lat/long pairs from the raw Plume Cassandra Table.
  */
def GetDistinctLatLongs() : Seq[Set[Double]] = {
  // Input : No input
  // OUTPUT : coordinates ---- Seq[Set]
  ???
}

/**
  * Applies the GoogleMapsRequester helper function to a Sequence of lat/long pairs.
  * Organizes the results into the GeoDictionary Cassandra Table, which is created on the spot. The table
  * is composed with the following columns:
  *
  * latitude : Double
  * longitude: Double
  * country: String
  * political: String
  * administrative_1 : String
  * geodata : UDT --- ask Daniel Gorham
  *
  */
def Geocoder(coordinates: Seq[Set[Double]]) : CassandraTable = {
// Input : coordinates ---- Sequence of unique lat/long pairs generated by GetDistinctLatLongs()
  // Output: GeoDictionary ---- Cassandra Table that maps each unique lat long to geographic metadata
  ???
}